shopping_list = list()
shopping_list.append('键盘')
# 对象.方法名（'商品'）
# 跟函数不同，函数名(对象)
shopping_list.append('键帽')
shopping_list.remove('键盘')
shopping_list.append('音响')
shopping_list.append('电竞椅')
print(shopping_list)
print(len(shopping_list))
print(shopping_list[0])
